### ISSUE TITLE
Bug: Clearpay not set as valid host 

### ISSUE THREAD

**Issue by JakeHoldom** [afterpay/sdk-ios#115]
# 🌎 Environment

 - OS Version: e.g. iOS 13.4.1
 - Version/Commit: e.g. 1.2.0

# 💬 Description

I'm not able to access Clearpay url links provided from the backend SDK as it's not set as a valid host in CheckoutWebViewController.
`private let validHosts: Set<String> = ["portal.afterpay.com", "portal.sandbox.afterpay.com"]`

# 🤔 Expected Results

Valid hosts should be:
`private let validHosts: Set<String> = ["portal.afterpay.com", "portal.sandbox.afterpay.com","portal.clearpay.co.uk", "portal.sandbox.clearpay.co.uk"`

**Comment by adamjcampbell** [comment]
Addressed in #116
