### ISSUE TITLE
Bug: Swift >= 5.2 Key Path Expressions

### ISSUE THREAD

**Issue by crherman7** [afterpay/sdk-ios#127]
# 🌎 Environment

 - OS Version: iOS 14.0 Xcode 12.0.1
 - Version/Commit: 1.0.4

# 💬 Description

Swift key path expressions are only valid in Swift version 5.2 or above unless provided a custom extension. The .podspec file denotes that 5.1 is the minimum necessary Swift version to be utilized. If developers are utilizing below 5.2 they will run into 
```
Type of expression is ambiguous without more context
```
at https://github.com/afterpay/sdk-ios/blob/ff409c61db080238e6b000220aa465c5b2589c36/Sources/Afterpay/Model/Configuration.swift#L104.

# 🦶 Reproduction Steps

1. Attempt to compile project with Afterpay SDK with Swift version 5.1

# 🤔 Expected Results

No error since the podspec denotes Swift version as 5.1.

# 😲 Actual Results

```
Type of expression is ambiguous without more context
```
at https://github.com/afterpay/sdk-ios/blob/ff409c61db080238e6b000220aa465c5b2589c36/Sources/Afterpay/Model/Configuration.swift#L104.

## Screenshots

![image](https://user-images.githubusercontent.com/17734240/103246806-c3606900-4932-11eb-8375-9ab2d1b4f516.png)

## Suggestion
1. Update https://github.com/afterpay/sdk-ios/blob/ff409c61db080238e6b000220aa465c5b2589c36/Afterpay.podspec#L14 to be `spec.swift_version = "5.2"` or include the appropriate extension to handle key path expressions.

**Comment by adamjcampbell** [comment]
Thanks @crherman7 I'll raise the requirements as it seems that the latest version cannot be used at the lower versions as it is.

**Comment by crherman7** [comment]
@adamjcampbell thank you for the quick change and release 🙏
