### ISSUE TITLE
Bug: 'Afterpay/Afterpay-Swift.h' file not found

### ISSUE THREAD

**Issue by fruitsw** [afterpay/sdk-ios#164]
# 🌎 Environment

 - OS Version: e.g. iOS 14.5
 - Version/Commit: e.g. 3.0

# 💬 Description

# 🦶 Reproduction Steps

1. pod install
2. import <Afterpay/Afterpay-Swift.h>

# 🤔 Expected Results

**Comment by huwr** [comment]
Hi @fruitsw  Thanks for this report.

I'm afraid I am unable to reproduce any errors with the steps you have described. Are there any additional things about your project we can check?
