### ISSUE TITLE
Feature: PriceBreaskdownView language based on configuration and not on phine language

### ISSUE THREAD

**Issue by GabrielMassana** [afterpay/sdk-ios#242]
# 🗣 Context

Our app language set up is based on user selection, not on device Settings. That means that the whole app change language if the user selects a different language.

# 🤝 Related Issues

PriceBreakdownView language is fully managed by the Device selected language. 
Even though some small things are managed by developers through [Configuration.locale](https://github.com/afterpay/sdk-ios/blob/master/Sources/Afterpay/Model/Configuration.swift), that does not apply to the text of teh view.

# 📝 Proposed Solution

Could be possible to add a flag to allow to use the Configuration.locale instead of the clientLocale?

I think the code that manage the current behaviour is this one:

```swift
internal func getRegionLanguage(merchantLocale: Locale, clientLocale: Locale) -> Locale? {
  return validRegionLanguages[merchantLocale.regionCode!]!.first {
    $0.languageCode == clientLocale.languageCode
  }
}
```

# 🔀 Alternative Solutions

# 🚫 Out of Scope

Thx

**Comment by ScottAntonacAP** [comment]
Hello @GabrielMassana,

Thank you for taking the time to raise this.

The reason for the way this is implemented is a legal / compliance one. The `PriceBreakdownView` contains an element that, when tapped, opens a modal containing terms and conditions. As this is a legal requirement, the locale of the modal needs to be correct for the merchant's country while being readable in the consumer's language. As there are only certain supported languages per merchant region, the consumer language is being handled by the device. When the language is not supported in the applicable merchant locale, the assets - including the price breakdown - will not be displayed.

A ticket has been raised internally [`EIT-2361`] to track further discussion on whether this enhancement will be implemented and prioritisation of the work. Any updates will be added to this GitHub issue.

Thank you.

**Comment by ScottAntonacAP** [comment]
Hello @GabrielMassana,

A new property has been added to `Configuration` in the latest release ([v5.4.0](https://github.com/afterpay/sdk-ios/releases/tag/5.4.0)). The new property is `consumerLocale`, which takes a `Locale` type. When set, this will override the `clientLocale`.

Thank you.
